[profile.default]
src = "src"
test = "tests"
script = "script"
out = "out"
libs = ["lib"]
cache_path = "cache"
solc_version = "0.8.24"
evm_version = "paris"
optimizer = true
optimizer_runs = 10_000
bytecode_hash = "none"
cbor_metadata = false
verbosity = 2
fs_permissions = [{ access = "read", path = "./" }]

[profile.default.fuzz]
runs = 1_000
max_test_rejects = 65_536

[profile.default.invariant]
runs = 256
depth = 128
fail_on_revert = false

[profile.ci]
verbosity = 3
fuzz = { runs = 5_000 }
invariant = { runs = 512, depth = 192, fail_on_revert = false }

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "long"
quote_style = "double"
number_underscore = "thousands"
wrap_comments = true
sort_imports = true
